# Generated by Django 5.1.3 on 2025-01-14 23:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipmentitem',
            old_name='shipment',
            new_name='shipment_id',
        ),
        migrations.RenameField(
            model_name='suppliers',
            old_name='zip',
            new_name='zip_code',
        ),
        migrations.RenameField(
            model_name='transferitem',
            old_name='transfer',
            new_name='transfer_item',
        ),
        migrations.RemoveField(
            model_name='warehousecontact',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='warehouses',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='warehouses',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='warehouses',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='shipments',
            name='service_code',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='warehousecontact',
            name='warehouse_contact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.warehouses'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventories',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item_groups',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item_lines',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='bill_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ship_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='item_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transferitem',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transferitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transferitem',
            name='item_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='warehouses',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='warehouses',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='inventories',
            table='api_inventories',
        ),
        migrations.AlterModelTable(
            name='shipments',
            table='api_shipments',
        ),
    ]
