# Generated by Django 5.1.3 on 2025-01-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_shipment_shipmentitem_shipment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='id',
            new_name='uid',
        ),
        migrations.AlterField(
            model_name='transfers',
            name='transfer_to',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
